#!/usr/bin/env python

import os
import re
import sys 
import time
import urllib2


def clear():
    if system() == 'Linux':
        os.system("clear")
    if system() == 'Windows':
        os.system('cls')
        os.system('color a')
    else:
        pass


def connect():
	os.system('openvpn --config vpnbook-us1-tcp80.ovpn')

def main():
	banner()
	unzip()
	getpass()
	connect()
	exit()
def exit():
	os.system('exit')
	print "\nCtrl + C -> Exiting!!"
if __name__ == '__main__':
	main()
